name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v1  # actions checkout, checkouts in my repo, a single commit; practic duce versiunea aia in VM unde ruleaza wf
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1  # after @ we can add a verions, a branch or a commit
        with: 
          who-to-greet: Ioana
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"